//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class TrabajosConexion : DbContext
    {
        public TrabajosConexion()
            : base("name=TrabajosConexion")
        {
            //para que lady loading funcione los campos deben estar en true

            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriasTrabajos> CategoriasTrabajos { get; set; }
        public virtual DbSet<TipoContrato> TipoContrato { get; set; }
        public virtual DbSet<Trabajos> Trabajos { get; set; }

        public override int SaveChanges()
        {
            foreach (var entry in this.ChangeTracker.Entries().Where(x => x.State == (EntityState)System.Data.Entity.EntityState.Added))
            {
                entry.Property("FechaRegistro").CurrentValue = DateTime.Now;
                entry.Property("FechaModificacion").CurrentValue = DateTime.Now;
                entry.Property("Estado").CurrentValue = true;
            }

            return base.SaveChanges();
        }
    }
}
